#! /usr/bin/env bash
#
#  get some stats of the reduced galaxies
#

#set -x

ext=12CO_rebase3_smooth1.3_hanning1.fits
ext=12CO_rebase3_smooth2_hanning2.fits
cbf=0.4
sum=summary.txt


ngc=$(grep ^NGC gals.pars | awk '{print $1}' | sort | uniq)
ugc=$(grep ^UGC gals.pars | awk '{print $1}' | sort | uniq)
cgc=$(grep ^CGC gals.pars | awk '{print $1}' | sort | uniq)

gals="$ngc $ugc $cgc"

echo $gals

log=do_all_stats.log

rm -f $log
for gal in $gals; do
    if [ -e ${gal}/${gal}_${ext} ]; then
        comment=$(txtpar $sum  p0=$gal,1,2)
	if [ -z $comment ]; then
	    comment="???"
	fi
	echo -n "$gal ${comment}" >> $log
	fitsccd ${gal}/${gal}_${ext} - |  ccdsub - - centerbox=$cbf,$cbf,$cbf | ccdstat - bad=0 qac=t >> $log
    fi
done

cat $log

# print out galaxy name and RMS in mK
echo "Galaxy      RMS [mK]  sratio($cbf) pratio     S/N   - for $ext"
awk '{printf("%-12s  %5.1f     %6.3f      %6.3f    %6.3f  %s\n",$1, 1000*$6,$10,  ($8+$7)/($8-$7), $8/$6, $2  )}' $log
