#! /usr/bin/env bash
#
#  get some stats of the reduced galaxies
#
#  Examples of noise RMS for NGC0001:
#  based on setting smooth_xy and smooth_v
#
#       basename                     RMS          xy   v        pixels           beam
#  12CO_rebase3_hanning0             65    mK     0    0     1.6" x 3.8 km/s      6.4"  
#  12CO_rebase3_hanning1             43           1    1     1.6" x 7.6           6.4
#  12CO_rebase3_smooth1.3_hanning1   23           1.3  1     1.6  x 7.6           8.3
#  12CO_rebase3_smooth2_hanning2      9.0         2    2     1.6  x 15           13
#  12CO_rebase3_smooth3_hanning3      4.6         3    3     1.6  x 30           19

#set -x

ext=12CO_rebase3_hanning1.fits
ext=12CO_rebase3_smooth1.3_hanning1.fits
ext=12CO_rebase3_smooth3_hanning3.fits
ext=12CO_rebase3_hanning0.fits
ext=12CO_rebase3_smooth2_hanning2.fits        # QL
ext=12CO_rebase3_hanning2.fits                # alberto
ext=12CO_rebase5_hanning2.fits                # alberto
ext=12CO_rebase5_smooth1.3_hanning2.fits      # new

cbf=0.4          # center fraction to compute noise
sum=summary.txt


ngc=$(grep ^NGC gals.pars | awk '{print $1}' | sort | uniq)
ugc=$(grep ^UGC gals.pars | awk '{print $1}' | sort | uniq)
cgc=$(grep ^CGC gals.pars | awk '{print $1}' | sort | uniq)
igc=$(grep ^IC  gals.pars | awk '{print $1}' | sort | uniq)
mkc=$(grep ^Mrk gals.pars | awk '{print $1}' | sort | uniq)


gals="$ngc $ugc $cgc $igc $mkc"



gals="NGC0001 NGC0495 NGC0169"



log=do_all_stats.tmp
export DEBUG=-1

rm -f $log
for gal in $gals; do
  galdirs="$(ls -d ${gal} sessions/${gal}__*)"
  for galdir in $galdirs; do
    if [ -e ${galdir}/${gal}_${ext} ]; then
	#tsys=$(txtpar $sum  p0=$gal,1,2)
	tsys=0
        #comment=$(txtpar $sum  p0=$gal,1,2)
	comment="$(grep -w ^$gal $sum | cut -d \  -f 2- )"
	if [ -z "$comment" ]; then
	    comment="???"
	fi
	if [ $tsys != 0 ]; then
	    n=$(echo $tsys | awk -F+ '{print NF}')
	    tsum=$(nemoinp "($tsys)/$n/sqrt($n)")
	    # echo "TSYS $gal,$tsys,$tsum"
	else
	    tsum=0
	fi
	nf=$(ls ${galdir}/*feed*.fits|wc -l)
	
	png=${galdir}/${gal}.dilsmomsk.mom0.png
	if [ -e $png ]; then
	    png=1
	else
	    png=0
	fi
	
	qac=$(fitsccd ${galdir}/${gal}_${ext} - |  ccdsub - - centerbox=$cbf,$cbf,$cbf | ccdstat - bad=0 qac=t)
	echo "$galdir $qac $nf $png $comment" >> $log

    fi
  done
done

# some lines with just a ' -' popped up in the $log
mv $log $log.tmp
awk '{if (NF>2) print $0}' $log.tmp > $log

# cat $log

# print out galaxy name and RMS in mK
echo "# Status summary of RMS stats of GBT EDGE QuickLook - produced via:   'make stats' on $(date)"
echo "#   Galaxy_$ext is basis for the statistics"
#echo "#                                                                       technicaly <Tsys> = SUM(Tsys)/(N*sqrt(N))"
#echo "#   Galaxy      RMS [mK]  sratio($cbf)   pratio       S/N  Tsys                     <Tsys> <Tsys>/RMS   detection?"
#awk '{printf("%3d %-12s  %5.1f     %6.3f      %6.3f    %6.3f  %-35s  %5.1f %4.1f %s\n",NR,$1, 1000*$8, $12, ($10+$9)/($10-$9), $10/$8, $2, $3, $3/(1000*$8), $4  )}' $log

#                                                                                                                                  notice only $13 could be present, but awk is ok
echo "#   Galaxy      RMS [mK]  sratio($cbf)   pratio       S/N   NF detection?"
awk '{printf("%3d %-12s  %5.1f     %6.3f      %6.3f    %6.3f  %3d %d %s %s %s %s\n", NR,  $1, 1000*$5,   $9,    ($7+$6)/($7-$6), $7/$5, $11, $12, $13,$14,$15,$16)}' $log 


echo "#  last updated on $(date)"
echo "#  sratio = (psum+nsum)/(psum-nsum)      0 (noise) to 1 (pure signal)"
echo "#  pratio = (max+min)/(max-min)          0 (noise)"


